config/routes.rb
Rails.application.routes.draw do
  resources :properties
  root to: 'home#index'

  resources :stocks
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user

  validate :check_funds

  def check_funds
    if user.bank - (price * shares) < 0
      errors.add(:shares, "Insufficient funds!")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :stocks
  has_many :properties
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
require 'yahoofinance'


class HomeController < ApplicationController
  def index
    # Set the type of quote we want to retrieve.
  # Available type are:
  #  - YahooFinance::StandardQuote
  #  - YahooFinance::ExtendedQuote
  #  - YahooFinance::RealTimeQuote


  # Set the symbols for which we want to retrieve quotes.
  # You can include more than one symbol by separating
  # them with a ',' (comma).


  # Get the quotes from Yahoo! Finance.  The get_quotes method call
  # returns a Hash containing one quote object of type "quote_type" for
  # each symbol in "quote_symbols".  If a block is given, it will be
  # called with the quote object (as in the example below).



  # You can get the same effect using the quote specific method.

  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:symbol, :shares, :purchased_price)
    end
end

app/controllers/stocks_controller.rb
require 'open-uri'
require 'json'
require 'net/http'

class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /stocks
  # GET /stocks.json
  def index

    @current_prices = []
    @properties = current_user.properties



    @properties.each do |stock|
      url = 'https://www.google.com/finance/info?q=NYSE%3A' + stock.symbol.to_s
      uri = URI(url)
      response = Net::HTTP.get(uri)
      json = JSON.parse(response[5..(response.length - 3)])
      current_price = json["l"].to_f
      @current_prices.push(current_price)
    end
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new(:symbol => params[:symbol])
    url = 'https://www.google.com/finance/info?q=NYSE%3A' + @stock.symbol.to_s
    uri = URI(url)
    response = Net::HTTP.get(uri)
    json = JSON.parse(response[5..(response.length - 3)])
    @stock.price = json["l"].to_f
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)
    @stock.user = current_user



    respond_to do |format|
      if @stock.save

            if Property.where(symbol: @stock.symbol).first
              property = Property.where(symbol: @stock.symbol).first
              property.shares = property.shares + @stock.shares
              property.purchased_price = property.purchased_price + (@stock.shares * @stock.price)
              property.save!
            else
              Property.create(symbol: @stock.symbol, purchased_price: @stock.price * @stock.shares, shares: @stock.shares, user: current_user)
            end
        current_user.bank = current_user.bank - (@stock.price * @stock.shares)
          format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
          format.json { render :show, status: :created, location: @stock }
          current_user.save!
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:user_id, :price, :shares, :symbol)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Suck It</p>
BUY



<%= form_tag("/stocks/new", method: "get") do %>
  <%= label_tag(:symbol, "Search for:") %>
  <%= text_field_tag(:symbol) %>
  <%= submit_tag("New") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockTrader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto navbar-right">
          <% if current_user %>
          <li class="nav-link active"><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li class="nav-link active"><%= link_to "Login", new_user_session_path %></li>
          <li class="nav-link active toggle-right"><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      <div>
    </nav>
    <%= yield %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  </body>

</html>

app/views/properties/_form.html.erb
<%= form_for(property) do |f| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %>
    <%= f.text_field :symbol %>
  </div>

  <div class="field">
    <%= f.label :shares %>
    <%= f.number_field :shares %>
  </div>

  <div class="field">
    <%= f.label :purchased_price %>
    <%= f.text_field :purchased_price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Shares</th>
      <th>Purchased price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.symbol %></td>
        <td><%= property.shares %></td>
        <td><%= property.purchased_price %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symbol:</strong>
  <%= @property.symbol %>
</p>

<p>
  <strong>Shares:</strong>
  <%= @property.shares %>
</p>

<p>
  <strong>Purchased price:</strong>
  <%= @property.purchased_price %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/stocks/_form.html.erb
<%= form_for(stock) do |f| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= stock.symbol %>


<%= stock.price %>
  <%= f.hidden_field(:symbol, :value => stock.symbol) %>
  <%= f.hidden_field(:price, :value => stock.price) %>

  <div class="field">
    <%= f.label :shares %>
    <%= f.number_field :shares %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Purchased Price</th>
      <th>Shares</th>
      <th>Current Price</th>
      <th>Current Value</th>
      <th>P/L</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each_with_index do |stock,index| %>
      <tr>
        <td><%= stock.symbol %></td>
        <td>$<%= stock.purchased_price %></td>
        <td><%= stock.shares %></td>
        <td>$<%= @current_prices[index] %></td>
        <td>$<%= stock[3].to_f * stock[2].to_f %></td>
        <td>$<%= (@current_prices[index] * stock.shares) - stock.purchased_price %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @stock.user.email %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @stock.symbol %>
</p>


<p>
  <strong>Price:</strong>
  <%= @stock.price %>
</p>

<p>
  <strong>Shares:</strong>
  <%= @stock.shares %>
</p>

<p>
  <strong>New Balance:</strong>
  <%= current_user.bank %>
</p>
<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>